# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- name: hny_api
  value: PZ36buubRdDSLZjeR4dUgB
- name: build_id
  value: $(Build.BuildId)
- name: build_start
  value: $(date +"%Y-%m-%d %T")
pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      curl -L -o buildevents https://github.com/honeycombio/buildevents/releases/latest/download/buildevents-linux-amd64
      chmod 755 buildevents
      cp -a buildevents /usr/local/bin/

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      export BUILDEVENT_APIKEY="$(hny_api)"
      export BUILD_ID="$(build_id)"
      echo "honeycomb api key: $BUILDEVENT_APIKEY"
      echo "build_id: $BUILD_ID"
      buildevents cmd ${BUILD_ID} 1 test-bash -- echo 'Hello world'

# - task: UseDotNet@2
#   inputs:
#     version: '7.x'

# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'build'
#     arguments: '--configuration $(buildConfiguration)'
#   displayName: 'dotnet build $(buildConfiguration)'

# - task: DotNetCoreCLI@2
#   displayName: 'dotnet test'
#   inputs:
#     command: 'test'
#     arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
#     publishTestResults: true
#     projects: 'intro-to-o11y-dotnet'

# - task: DotNetCoreCLI@2
#   inputs:
#     command: publish
#     publishWebProjects: True
#     arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
#     zipAfterPublish: True

# # this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
# - task: PublishPipelineArtifact@1
#   inputs:
#     targetPath: '$(Build.ArtifactStagingDirectory)' 
#     artifactName: 'intro-to-o11y-dotnet'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      BUILDEVENT_APIKEY="$(hny_api)"
      BUILD_ID="$(build_id)"
      BUILD_START="$(build_start)"
      echo "build start time: ${BUILD_START}"
      trace_link=$(buildevents build ${BUILD_ID} ${BUILD_START} success)
      echo "Build Events URL: ${trace_link}"